# Generated by Django 4.0.5 on 2022-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[('A', 'ACTION'), ('D', 'DRAMA'), ('C', 'COMEDY'), ('R', 'ROMANCE'), ('H', 'HORROR')], default='A', max_length=1)),
                ('language', models.CharField(choices=[('EN', 'ENGLISH'), ('AR', 'ARABIC')], default='EN', max_length=2)),
                ('status', models.CharField(choices=[('R', 'RECENTLY ADDED'), ('M', 'MOST WATCHED'), ('T', 'TOP RATED')], default='R', max_length=1)),
                ('year_of_production', models.DateField()),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
