# Generated by Django 4.0.5 on 2022-06-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_cast_movielinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('arabic', 'ARABIC')], default='english', max_length=10),
        ),
    ]
