# Generated by Django 4.0.5 on 2022-06-06 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 16, 24, 34, 470248, tzinfo=utc)),
        ),
    ]
